#!/bin/bash -eu

mkdir -p ~/.ssh/
echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
head ~/.ssh/id_rsa -n 2
chmod 600 ~/.ssh/id_rsa

ssh-keyscan github.com >> ~/.ssh/known_hosts
git config --global user.name 'wei.feng'
git config --global user.email 'wei.feng'

hexo generate && hexo Deploy
