name: Main Workflow
on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - name: Code checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: npm

    - name: Markdown link check
      uses: gaurav-nelson/github-action-markdown-link-check@v1

    - name: Build dependencies
      run: auto/build

    - name: Deploy to GitHub Pages
      env:
        GH_ACTION_DEPLOY_KEY: ${{secrets.GH_ACTION_DEPLOY_KEY}}
      run: auto/deploy
